# Generated by Django 6.0.3 on 2026-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='viewer', max_length=12),
        ),
    ]
